services:
  server:
    build:
      context: .
      dockerfile: dockers/Dockerfile.server
    ports:
      - '5001:5001'

  app:
    build:
      context: .
      dockerfile: dockers/Dockerfile.app
    ports:
      - '10000:10000'
    depends_on:
      - server
