services:
  server:
    build:
      context: .
      dockerfile: dockers/Dockerfile.server
    ports:
      - '4000:4000'

  app:
    build:
      context: .
      dockerfile: dockers/Dockerfile.app
    ports:
      - '9000:9000'
    depends_on:
      - server
