FROM oven/bun:slim AS build
WORKDIR /dklb

COPY ./server ./

RUN sed -i '/"@dklb\/eslint-config": "workspace:\^"/d' ./package.json && \
    sed -i '/"@dklb\/tsconfig": "workspace:\^"/d' ./package.json

RUN bun install --production --ignore-scripts && \
    bun run build

FROM oven/bun:slim
WORKDIR /dklb
COPY --from=build /dklb/dist/index.js /dklb/index.js

EXPOSE 4000
ENTRYPOINT ["bun", "run", "/dklb/index.js"]
